name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Yarn Works
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
          cache-dependency-path: ./website/yarn.lock
          
      - name: Use Yarn Works 2
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: ./website/yarn.lock
          
      - uses: actions/setup-node@v3        
        with:
          node-version: 16
          check-latest: true
          cache: "npm"
          cache-dependency-path: sub/package-lock.json
